name: Build Custom CircuitPython Firmware

on:
  workflow_dispatch:
    inputs:
      circuitpython_version:
        description: 'CircuitPython Version (e.g., 9.2.8)'
        required: true
        default: '9.2.8'
      board_name:
        description: 'Target Board Name (e.g., yd_esp32_s3_n16r8)'
        required: true
        default: 'yd_esp32_s3_n16r8'

  push:
    branches:
      - main # Or your preferred branch

jobs:
  build_firmware:
    runs-on: ubuntu-latest
    container:
      image: espressif/idf:v5.1.2 # Or v5.2.1, v5.3.1

    steps:
    - name: Set Git Safe Directory & Checkout CircuitPython Fork
      # Run the safe.directory command here, before actions/checkout does its work.
      # This is done by adding a pre-script to the action.
      # However, actions/checkout doesn't directly support a pre-script in this way.
      # So, we'll do it in a separate step right before.
      run: |
        echo "Marking ${GITHUB_WORKSPACE} as a safe Git directory..."
        # The GITHUB_WORKSPACE might not be populated yet in this very first step if run separately.
        # So we use the known path structure for the runner.
        # The workspace is typically /__w/reponame/reponame
        # Let's find the repo name dynamically
        REPO_NAME=$(echo "${{ github.repository }}" | cut -d'/' -f2)
        WORKSPACE_PATH="/__w/${REPO_NAME}/${REPO_NAME}"
        echo "Calculated workspace path: ${WORKSPACE_PATH}"
        git config --global --add safe.directory "${WORKSPACE_PATH}"
      # This step above might still be too late for actions/checkout itself.
      # A more robust way is to ensure the runner user has permissions, or use a container where this is not an issue.
      # For now, let's keep the safe.directory in the script block below as well.

    - name: Checkout CircuitPython Fork & Fetch All Tags
      uses: actions/checkout@v4
      with:
        repository: ${{ github.repository }} # Checks out YOUR fork
        fetch-depth: 0 # Fetches all history and all tags.
        submodules: 'false' # We will handle submodules after checking out the specific tag

    - name: Get CircuitPython Version from Input or Default
      id: cp_version
      run: echo "version=${{ github.event.inputs.circuitpython_version || '9.2.8' }}" >> $GITHUB_OUTPUT

    - name: Get Board Name from Input or Default
      id: board_info
      run: echo "name=${{ github.event.inputs.board_name || 'yd_esp32_s3_n16r8' }}" >> $GITHUB_OUTPUT

    - name: Checkout Specific Version & Update Submodules
      working-directory: ${{ github.workspace }}
      run: |
        # Ensure safe directory for this script's git operations
        echo "Re-confirming ${GITHUB_WORKSPACE} as a safe Git directory for this step..."
        git config --global --add safe.directory "${GITHUB_WORKSPACE}"
        
        echo "Available tags (first 20 before explicit fetch):"
        git tag | sort -V | tail -n 20 # List some tags for debugging, sorted

        echo "Fetching all tags (again, to be absolutely sure)..."
        git fetch --all --tags --prune --force 
        
        echo "Available tags (first 20 after explicit fetch):"
        git tag | sort -V | tail -n 20 # List some tags for debugging, sorted

        echo "Checking out tag: ${{ steps.cp_version.outputs.version }}"
        # Try a more direct checkout of the tag. If it's an annotated tag, this might need adjustment.
        # Using 'git checkout tags/TAG_NAME' is often more robust for annotated tags.
        if git rev-parse --verify --quiet "refs/tags/${{ steps.cp_version.outputs.version }}"; then
          git checkout "tags/${{ steps.cp_version.outputs.version }}"
        else
          echo "Tag ${{ steps.cp_version.outputs.version }} not found directly, trying without 'tags/' prefix"
          git checkout "${{ steps.cp_version.outputs.version }}"
        fi
        
        echo "Updating submodules (this may take a while)..."
        git submodule update --init --recursive

    # ... (Rest of your workflow: Install Python Deps, Modify mpconfigboard.mk, etc.) ...
    # (The rest of the YML from the previous "full updated workflow" message should follow here)
    - name: Install CircuitPython's Python Build Dependencies
      working-directory: ${{ github.workspace }}
      run: |
        pip install --upgrade pip
        if [ -f "tools/requirements-build.txt" ]; then
          pip install -r tools/requirements-build.txt
        elif [ -f "requirements-build.txt" ]; then
          pip install -r requirements-build.txt
        else
          echo "WARNING: Build requirements file not found."
        fi

    - name: Modify mpconfigboard.mk for I2SIn (if not already committed)
      working-directory: ${{ github.workspace }}
      run: |
        BOARD_CONFIG_PATH="ports/espressif/boards/${{ steps.board_info.outputs.name }}/mpconfigboard.mk"
        if [ -f "$BOARD_CONFIG_PATH" ]; then
          echo "Modifying $BOARD_CONFIG_PATH to enable I2SIn..."
          sed -i 's/^\(CIRCUITPY_AUDIOBUSIO_I2S_IN\s*=\s*\)0/\11/' "$BOARD_CONFIG_PATH"
          echo "Contents after modification:"
          cat "$BOARD_CONFIG_PATH"
        else
          echo "ERROR: Board config file $BOARD_CONFIG_PATH not found!"
          exit 1
        fi

    - name: Install ESP-IDF Toolchain via Submodule Script
      working-directory: ${{ github.workspace }}/ports/espressif
      run: |
        echo "Installing ESP-IDF tools for target esp32s3 using submodule's install.sh..."
        ./esp-idf/install.sh esp32s3

    - name: Build Firmware
      working-directory: ${{ github.workspace }}/ports/espressif
      run: |
        echo "Sourcing ESP-IDF environment and building for board: ${{ steps.board_info.outputs.name }}"
        source ./esp-idf/export.sh
        make BOARD=${{ steps.board_info.outputs.name }} -j$(nproc)

    - name: Upload Firmware Artifacts (BIN only)
      uses: actions/upload-artifact@v4
      with:
        name: firmware-bin-${{ steps.board_info.outputs.name }}-${{ steps.cp_version.outputs.version }}
        path: |
          ${{ github.workspace }}/ports/espressif/build-${{ steps.board_info.outputs.name }}/bootloader/bootloader.bin
          ${{ github.workspace }}/ports/espressif/build-${{ steps.board_info.outputs.name }}/partition_table/partition-table.bin
          ${{ github.workspace }}/ports/espressif/build-${{ steps.board_info.outputs.name }}/circuitpython.bin
        if-no-files-found: error
