name: Build Custom CircuitPython Firmware

on:
  workflow_dispatch:
    inputs:
      circuitpython_version:
        description: 'CircuitPython Version (e.g., 9.2.8)'
        required: true
        default: '9.2.8'
      board_name:
        description: 'Target Board Name (e.g., yd_esp32_s3_n16r8)'
        required: true
        default: 'yd_esp32_s3_n16r8'

  push:
    branches:
      - main # Or your preferred branch

jobs:
  build_firmware:
    runs-on: ubuntu-latest
    container:
      image: espressif/idf:v5.1.2 # Or v5.2.1, v5.3.1 (check CP docs for compatibility with 9.2.8)

    steps:
    - name: Checkout CircuitPython Fork (Full Depth with Tags)
      uses: actions/checkout@v4
      with:
        repository: ${{ github.repository }} # Checks out YOUR fork
        fetch-depth: 0 # IMPORTANT: Fetches all history AND tags of your fork.
        # submodules: 'false' # Default is false, explicit is fine too.
        # set-safe-directory: true # Default is true, explicit is fine too.

    - name: Get CircuitPython Version from Input or Default
      id: cp_version
      run: echo "version=${{ github.event.inputs.circuitpython_version || '9.2.8' }}" >> $GITHUB_OUTPUT

    - name: Get Board Name from Input or Default
      id: board_info
      run: echo "name=${{ github.event.inputs.board_name || 'yd_esp32_s3_n16r8' }}" >> $GITHUB_OUTPUT

    - name: Fetch Upstream Tags, Checkout Specific Version & Update Submodules
      working-directory: ${{ github.workspace }}
      run: |
        echo "Configuring Git safe directory for this script's operations..."
        # This ensures your explicit git commands in this block are fine
        git config --global --add safe.directory "${GITHUB_WORKSPACE}"
        
        echo "Adding upstream remote (adafruit/circuitpython)..."
        git remote add upstream https://github.com/adafruit/circuitpython.git
        
        echo "Fetching all tags from upstream (adafruit/circuitpython)..."
        # This is the crucial fetch for getting official release tags
        git fetch upstream --tags --prune --force 
        
        echo "--- All available local tags after fetching upstream (sorted, last 50) ---"
        git tag | sort -V | tail -n 50 
        echo "--- End of tag list ---"

        echo "Attempting to checkout tag: ${{ steps.cp_version.outputs.version }}"
        CP_TAG_TO_CHECKOUT="${{ steps.cp_version.outputs.version }}"
        
        # Create a temporary local branch from the tag to avoid detached HEAD.
        # 'git checkout tags/TAG_NAME -b branch_name' is robust.
        if git checkout "tags/$CP_TAG_TO_CHECKOUT" -b temp-build-branch; then
          echo "Successfully checked out tags/$CP_TAG_TO_CHECKOUT to new branch temp-build-branch"
        elif git checkout "$CP_TAG_TO_CHECKOUT" -b temp-build-branch; then
           echo "Successfully checked out $CP_TAG_TO_CHECKOUT directly to new branch temp-build-branch (fallback)"
        else
          echo "ERROR: Could not checkout tag $CP_TAG_TO_CHECKOUT."
          echo "Please examine the tag list above to see if the tag is present and correctly named."
          # List all tags if checkout fails, for better debugging
          echo "All available tags from local repository (after upstream fetch):"
          git tag
          exit 1
        fi
        
        echo "Updating submodules (this may take a while)..."
        git submodule update --init --recursive

    - name: Install CircuitPython's Python Build Dependencies
      working-directory: ${{ github.workspace }}
      run: |
        pip install --upgrade pip
        if [ -f "tools/requirements-build.txt" ]; then
          pip install -r tools/requirements-build.txt
        elif [ -f "requirements-build.txt" ]; then
          pip install -r requirements-build.txt
        else
          echo "WARNING: Build requirements file not found."
        fi

    # --- IMPORTANT ---
    # IF YOU HAVE ALREADY COMMITTED YOUR 'mpconfigboard.mk' CHANGE 
    # (CIRCUITPY_AUDIOBUSIO_I2S_IN = 1) TO YOUR FORK,
    # THEN REMOVE OR COMMENT OUT THIS NEXT "Modify mpconfigboard.mk" STEP.
    - name: Modify mpconfigboard.mk for I2SIn (if not already committed)
      working-directory: ${{ github.workspace }}
      run: |
        BOARD_CONFIG_PATH="ports/espressif/boards/${{ steps.board_info.outputs.name }}/mpconfigboard.mk"
        if [ -f "$BOARD_CONFIG_PATH" ]; then
          echo "Modifying $BOARD_CONFIG_PATH to enable I2SIn..."
          sed -i 's/^\(CIRCUITPY_AUDIOBUSIO_I2S_IN\s*=\s*\)0/\11/' "$BOARD_CONFIG_PATH"
          echo "Contents after modification:"
          cat "$BOARD_CONFIG_PATH"
        else
          echo "ERROR: Board config file $BOARD_CONFIG_PATH not found!"
          exit 1
        fi

    - name: Install ESP-IDF Toolchain via Submodule Script
      working-directory: ${{ github.workspace }}/ports/espressif
      run: |
        echo "Installing ESP-IDF tools for target esp32s3 using submodule's install.sh..."
        ./esp-idf/install.sh esp32s3

    - name: Build Firmware
      working-directory: ${{ github.workspace }}/ports/espressif
      run: |
        echo "Sourcing ESP-IDF environment and building for board: ${{ steps.board_info.outputs.name }}"
        source ./esp-idf/export.sh
        make BOARD=${{ steps.board_info.outputs.name }} -j$(nproc)

    - name: Upload Firmware Artifacts (BIN only)
      uses: actions/upload-artifact@v4
      with:
        name: firmware-bin-${{ steps.board_info.outputs.name }}-${{ steps.cp_version.outputs.version }}
        path: |
          ${{ github.workspace }}/ports/espressif/build-${{ steps.board_info.outputs.name }}/bootloader/bootloader.bin
          ${{ github.workspace }}/ports/espressif/build-${{ steps.board_info.outputs.name }}/partition_table/partition-table.bin
          ${{ github.workspace }}/ports/espressif/build-${{ steps.board_info.outputs.name }}/circuitpython.bin
        if-no-files-found: error
